---
title: 'Neuroecon 2018 poster figures'
output:
github_document:
toc: yes
toc_float: yes
---

```{r}
p1 = boot_df %>%
  group_by(dv) %>%
  summarise(mean_icc = mean(icc),
            rt_acc = unique(rt_acc),
            overall_difference = unique(overall_difference),
            raw_fit = unique(raw_fit)) %>%
  mutate(rt_acc = as.character(rt_acc)) %>%
  ggplot(aes(factor(raw_fit, levels = c("raw", "EZ", "hddm"), labels=c("Raw", "EZ-diffusion", "Hierarchical diffusion")), mean_icc, fill=factor(rt_acc, levels = c("rt","accuracy", "drift rate", "threshold", "non-decision"), labels=c("Response Time", "Accuracy","Drift Rate", "Threshold", "Non-decision"))))+
  geom_boxplot()+
  facet_wrap(~factor(overall_difference, levels = c("non-contrast", "contrast", "condition"), labels = c("Non-contrast", "Contrast", "Condition")))+
  ylab("ICC")+
  xlab("")+
  theme(legend.title = element_blank(),
        legend.position = 'bottom',
        axis.text = element_text(size=36),
        axis.title.y = element_text(size=36), 
        strip.text = element_text(size=36),
        legend.text = element_text(size=36),
        legend.spacing.x = unit(0.4, "cm"),
        legend.key.size = unit(2, "cm"))+
  scale_y_continuous(breaks = seq(-1,1,0.5),
                     limits = c(-0.5,1))

ggsave('Boot_ddm_plot.jpeg', device = "jpeg", plot=p1, path = "../output/figures/", width = 38, height = 8, units = "in", limitsize = FALSE, dpi = 300)

```


```{r}
tmp = rel_df_sample_size %>% 
  group_by(sample_size) %>%
  summarise(mean_icc = mean(icc,na.rm=T),
            sem_icc = sem(icc), 
            mean_var_subs_pct = mean(var_subs_pct,na.rm=T),
            sem_var_subs_pct = sem(var_subs_pct),
            mean_var_ind_pct = mean(var_ind_pct, na.rm=T),
            sem_var_ind_pct = sem(var_ind_pct),
            mean_var_resid_pct = mean(var_resid_pct,na.rm=T),
            sem_var_resid_pct = sem(var_resid_pct))

rel_df_sample_size_summary %>%
  na.omit() %>%
  ggplot(aes(factor(sample_size), mean_icc))+
  geom_line(aes(group = dv), alpha = 0.1)+
  geom_line(data = tmp,aes(factor(sample_size),mean_icc, group=1), color="magenta", size=2)+
  geom_point(data = tmp,aes(factor(sample_size),mean_icc), color="magenta", size=4)+
  geom_errorbar(data = tmp,aes(ymin=mean_icc-sem_icc, ymax = mean_icc+sem_icc), color="magenta", width = 0.1, size=2)+
  ylab("Mean reliability 100 \n  samples of size n")+
  xlab("Sample size")+
  ylim(-1,1)+
  theme(axis.text = element_text(size=36),
        axis.title= element_text(size=32))

ggsave('Sample_size.jpeg', device = "jpeg", path = "../output/figures/", width = 14, height = 5, units = "in", limitsize = FALSE, dpi = 300)
```

```{r}
flat_difference %>%
  mutate(par = factor(par, levels = c("drift", "non_decision", "thresh"), labels = c("Drift Rate", "Non-decision", "Threshold")),
         time = factor(time, levels = c("test", "retest"), labels = c("Test", "Retest"))) %>%
  ggplot(aes(hierarchical, flat))+
  geom_point(aes(color = par, shape = par, alpha=time), size=4)+
  geom_abline(aes(intercept=0, slope=1), color="black", linetype="dashed")+
  xlim(-5,5)+
  ylim(-5,5)+
  theme(legend.position = "bottom",
        legend.title = element_blank(),
        axis.text = element_text(size=16),
        axis.title= element_text(size=22),
        legend.text = element_text(size=16),
        #legend.spacing.x = unit(0.4, "cm"),
        #legend.key.size = unit(4, "cm"),
        # legend.box = "vertical",
        legend.box.margin = margin(.2, .2, .2, .2))+
  scale_alpha_discrete(range = c(0.4, 0.8))+
  xlab("Hierarchical Estimate")+
  ylab("Non-hierarchical Estimate")

ggsave('Flat_vs_hier_est.jpeg', device = "jpeg", path = "../output/figures/", width = 7, height = 6, units = "in", limitsize = FALSE, dpi = 300)
```

```{r}
rel_df_flat %>%
  mutate(rt_acc = factor(rt_acc, levels = c("drift rate", "non-decision", "threshold"), labels = c("Drift Rate", "Non-decision", "Threshold"))) %>%
  ggplot(aes(icc.y, icc.x, color = rt_acc))+
  geom_point(size=4)+
  geom_abline(aes(slope=1, intercept = 0), color="black", linetype = "dashed")+
  xlab("Reliability of hierarchical estimate")+
  ylab("Reliability of \n non-hierarchical estimate")+
  theme(legend.position = "bottom",
        legend.title = element_blank(),
        axis.text = element_text(size=16),
        axis.title= element_text(size=22),
        legend.text = element_text(size=16))

ggsave('Flat_vs_hier_rel.jpeg', device = "jpeg", path = "../output/figures/", width = 7, height = 6, units = "in", limitsize = FALSE, dpi = 300)
```

```{r}
rel_df_dvs %>%
  left_join(measure_labels[,c("dv", "rt_acc")], by="dv") %>%
  ggplot(aes(icc, fill=rt_acc))+
  geom_density(position="identity",alpha=0.5, color=NA)+
  theme(legend.title = element_blank(),
        legend.position = "bottom",
        axis.text = element_text(size=16),
        axis.title= element_text(size=22),
        legend.text = element_text(size=16))+
  xlab("Retest reliability")+
  geom_vline(xintercept=rel_df_factors$icc[rel_df_factors$dim_name=="drift_rate"], color="#E495A5", size=1.5)+
  geom_vline(xintercept=rel_df_factors$icc[rel_df_factors$dim_name=="non-decision"], color="#86B875", size=1.5)+
  geom_vline(xintercept=rel_df_factors$icc[rel_df_factors$dim_name=="threshold"], color="#7DB0DD", size=1.5)+
  xlim(-1, 1)

ggsave('EZ_clust_rel.jpeg', device = "jpeg", path = "../output/figures/", width = 7, height = 6, units = "in", limitsize = FALSE, dpi = 300)
```

```{r}
ez_measures_pred = read.csv(paste0(input_path, 'ez_measures_pred.csv'))
ez_factors_pred = read.csv(paste0(input_path, 'ez_factors_pred.csv'))

ez_measures_pred = ez_measures_pred %>% na.exclude()
ez_factors_pred = ez_factors_pred %>% na.exclude()

tmp1=ez_factors_pred %>%
  group_by(dv) %>%
  summarise(mean_r2 = mean(Rsquared),
            sem_r2 = sem(Rsquared)) %>%
  mutate(pred="factor")

tmp2 = ez_measures_pred %>%
  group_by(dv) %>%
  summarise(mean_r2 = mean(Rsquared), #%>%
            sem_r2 = sem(Rsquared)) %>%
  mutate(pred = "measure")

rbind(tmp1,tmp2) %>%
  ggplot(aes(dv, mean_r2, fill=pred))+
  geom_bar(stat="identity", position = position_dodge(width = 0.9), alpha=0.75)+
  geom_errorbar(aes(ymin=mean_r2-sem_r2, ymax = mean_r2+sem_r2),position = position_dodge(width = 0.9), width = 0.25)+
  xlab("")+
  ylab(expression('Mean R'^2))+
  theme(legend.position = "bottom",
        legend.title = element_blank(),
        axis.text.y = element_text(size=16),
        axis.text.x = element_text(size=14),
        axis.title= element_text(size=22),
        legend.text = element_text(size=16))+
  scale_fill_manual(values=c("#E69F00", "#56B4E9"))

ggsave('fvsm_pred.jpeg', device = "jpeg", path = "../output/figures/", width = 14, height = 6, units = "in", limitsize = FALSE, dpi = 300)
```